### ISSUE TITLE
Loading fixtures with foreign keys

### ISSUE THREAD

**Issue by rapvelopment** [domasx2/sequelize-fixtures#56] opened 2016-05-16 11:54 UTC
Hi,

I have been trying to use sequelize-fixtures to build a database that includes foreign keys, but when I do, I get the following error

 [TypeError: Object #<Object> has no method 'replace'].

The main code db-create.js is

```
'user strict';
var Sequelize = require('sequelize');
var sequelize_fixtures = require('sequelize-fixtures');

var sf = require('./index')
sf.sequelize.sync().then(function(r) {
        var constant_models = {
                UserType: sf.UserType,
                User: sf.User
        };

        var models = {
                User: sf.User
        };

        sequelize_fixtures.loadFile('./constants.json', constant_models).then(function(r) {
                console.log("success loading!");
        }, function(err) {
                console.log("loading constants");
                console.log(err);
        });
}, function(err) {
        console.log('error syncing', err)
});
```

index.js is:

```
var Sequelize = require('sequelize');

var sequelize = new Sequelize('db', 'usr', 'pwd', {
        host: 'localhost',
        port: '5432',
        dialect: 'postgres',
        pool: false
});

exports.sequelize = sequelize
exports.all = [];
var schemaName = 'test'
exports.schemaName = schemaName
sequelize.createSchema(schemaName);


['UserType', 'User'].forEach(function(model) {
        var mod = require('./' + model)(sequelize, Sequelize, schemaName);
        module.exports[model] = mod;
        exports.all.push(mod);
});

(function(m){
        m.User.belongsTo(m.UserType, {
                foreignKey: {
                        name: 'fk_user_type',
                        allowNull: false
                }
        });
        m.UserType.hasMany(m.User, {
                foreignKey: 'fk_user_type',
                allowNull: false
        });
})(exports);

```

UserType.js is:

```
'use strict';
module.exports = function(sequelize, DataTypes, schema) {

        var UserType = sequelize.define('user_types', {
                id: {
                        type: DataTypes.INTEGER,
                        autoIncrement: true,
                        primaryKey: true,
                        allowedNull: false
                },
                userType: {
                        type: DataTypes.STRING,
                        field: 'user_type',
                        unique: true,
                        allowedNull: false
                }
        }, {
                freezeTableName: true,
                schema: schema,
                underscored: true,
                underscoredAll: true
        });

        return UserType;
};

```

and User.js is:

```
'use strict';

module.exports = function(sequelize, DataTypes, schema) {
        var User = sequelize.define('users', {
                id: {
                        type: DataTypes.INTEGER,
                        autoIncrement: true,
                        primaryKey: true,
                        allowedNull: false
                },
                firstName: {
                        type: DataTypes.STRING,
                        field: 'first_name',
                        allowNull: false,
                        unique: 'users_uq1'
                },
                lastName: {
                        type: DataTypes.STRING,
                        field: 'last_name',
                        allowNull: false,
                        unique: 'users_uq1'
                },
                email: {
                        type: DataTypes.STRING,
                        allowNull: false,
                        unique: true,
                        validate: {
                                isEmail: true
                        }
                },
                salt: {
                        type: DataTypes.STRING,
                        allowNull: false,
                        unique: true
                },
                password: {
                        type: DataTypes.STRING,
                        allowNull: false,
                        unique: true
                },
                lastLogin: {
                       type: DataTypes.DATE,
                        field: 'last_login',
                        allowNull: false,
                        validate: {
                                isDate: true,
                                isAfter: '2016-01-01'
                        }
                }
        }, {
                freezeTableName: true,
                schema: schema,
                underscored: true,
                underscoredAll: true

        });
        return User;
};

```

The data, constants.json, is

```
[{
        "model": "UserType",
        "data": {
                "userType": "Administrator"
        }
},{
        "model": "User",
        "data": {
                "firstName": "D",
                "lastName": "R",
                "email": "d@aol.com",
                "lastLogin": "2016-02-01",
                "salt": "brownies",
                "password": "pass",
                "fk_user_type": {
                        "userType": "Administrator"
                }
        }
},{
        "model": "User",
        "data": {
                "firstName": "j",
                "lastName": "r",
                "email": "R.J@gmail.com",
                "lastLogin": "2016-02-01",
                "password": "password",
                "fk_user_type": {
                        "userType": "Administrator"
                }
        }
}]
```

Any help or suggestions would be appreciated!

**Comment by domasx2** [comment] 2016-05-16 16:28
hi, can you paste the stack trace?

**Comment by kenydub** [comment] 2016-05-16 22:05
```
r_types" WHERE "user_types"."user_type" = 'Administrator' LIMIT 1;
Unhandled rejection TypeError: Object #<Object> has no method 'replace'
    at Object.SqlString.escape (/home/rapture/hockey/db/node_modules/sequelize/lib/sql-string.js:61:15)
    at Object.QueryGenerator.escape (/home/rapture/hockey/db/node_modules/sequelize/lib/dialects/abstract/query-generator.js:977:22)
    at Object.QueryGenerator.whereItemQuery (/home/rapture/hockey/db/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2242:22)
    at /home/rapture/hockey/db/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1873:25
    at /home/rapture/hockey/db/node_modules/sequelize/node_modules/lodash/lodash.js:4389:15
    at baseForOwn (/home/rapture/hockey/db/node_modules/sequelize/node_modules/lodash/lodash.js:2652:24)
    at Function.forOwn (/home/rapture/hockey/db/node_modules/sequelize/node_modules/lodash/lodash.js:12254:24)
    at Object.QueryGenerator.whereItemsQuery (/home/rapture/hockey/db/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1872:9)
    at Object.QueryGenerator.getWhereConditions (/home/rapture/hockey/db/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2307:19)
    at Object.QueryGenerator.selectQuery (/home/rapture/hockey/db/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1458:28)
    at QueryInterface.select (/home/rapture/hockey/db/node_modules/sequelize/lib/query-interface.js:661:25)
    at null.<anonymous> (/home/rapture/hockey/db/node_modules/sequelize/lib/model.js:1413:32)
    at tryCatcher (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:415:13)

```

**Comment by domasx2** [comment] 2016-05-17 06:00
The problem is: On User model, accessor for UserType relation is 'UserType', so you should use that to assign UserType to User, example below. 
 'fk_user_type' is the foreign key column on the users table.  You can also use it I think, but it will only accept an integer (id of a UserType row).

```json
[{
        "model": "UserType",
        "data": {
                "userType": "Administrator"
        }
},{
        "model": "User",
        "data": {
                "firstName": "D",
                "lastName": "R",
                "email": "d@aol.com",
                "lastLogin": "2016-02-01",
                "salt": "brownies",
                "password": "pass",
                "UserType": {
                        "userType": "Administrator"
                }
        }
},{
        "model": "User",
        "data": {
                "firstName": "j",
                "lastName": "r",
                "email": "R.J@gmail.com",
                "lastLogin": "2016-02-01",
                "password": "password",
                "UserType": {
                        "userType": "Administrator"
                }
        }
}]
```

I've been meaning to work on validating data and providing nicer warnings/errors, will try to get around to it sooner rather than later.

**Comment by kenydub** [comment] 2016-05-17 10:52
Thanks. If I remove the foreign key and not null constraints, everything works but the foreign key `user_type_id` column in table `users` is not populated. 

If I remove the foreign key definitions from index.js but leave the not null restriction, I get the following error:
```
nhandled rejection SequelizeValidationError: notNull Violation: user_type_id cannot be null
    at /home/rapture/hockey/db/node_modules/sequelize/lib/instance-validator.js:74:14
    at tryCatcher (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:628:18)
    at PromiseArray._resolve (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:564:26)
    at Promise._settlePromise0 (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/home/rapture/hockey/db/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:415:13)

```

**Comment by georgeedwards** [comment] 2017-01-21 13:21
@domasx2  I think I am facing the same issue... 

**models/cell.ts**
```
export default function defineCell(sequelize: Sequelize.Sequelize, DataTypes) {
    var Cell = sequelize.define<CellInstance, CellAttributes>('Cell', {
        name: { type: Sequelize.STRING, unique: true },
        oee: Sequelize.INTEGER,
        tal: Sequelize.INTEGER,
        target: Sequelize.INTEGER
    });
    Cell.associate = function (models) {
        Cell.hasMany(models.Line);
    }
    return Cell;
};
```

**models/site.ts**

```
export default function defineSite(sequelize: Sequelize.Sequelize, DataTypes) {
    var Site = sequelize.define<SiteInstance, SiteAttributes>('Site', {
        name: { type: Sequelize.STRING, unique: true },
        oee: Sequelize.INTEGER,
        tal: Sequelize.INTEGER,
        target: Sequelize.INTEGER
    });
    Site.associate = function (models) {
        Site.hasMany(models.Cell)
    }
    return Site;
};
```
**data.json**
```
[
    {
        "model": "Site",
        "data": {
            "name": "Ashford",
            "oee": 86,
            "tal": 26000,
            "target": 80
        }
    },
    {
        "model": "Cell",
        "data": {
            "name": "Powders",
            "oee": 88,
            "tal": 20000,
            "target": 80,
            "SiteId": {
                "name": "Ashford"
            }
        }
    }]
```

however the `SiteId` property causes the following error:

> [0] Fixtures: reading file C:/Users/George/Source/Repos/Coty%20Monitoring%20System/server/seeders/default.json...
[0] Unhandled rejection TypeError: val.replace is not a function

**Comment by sdotson** [comment] 2017-10-05 19:27
Did you ever figure this issue out? currently troubleshooting the same exact thing.

**Comment by matmar10** [comment] 2019-04-22 14:31
Closing this since it's a general help question and old.

**Closed by matmar10** 2019-04-22 14:31 UTC
