### ISSUE TITLE
Error with belongsToMany

### ISSUE THREAD

**Issue by Sk1Zy** [domasx2/sequelize-fixtures#32] opened 2015-05-28 14:28 UTC
Hi

I'm having a problem since i updated sequelize to version 3.1.1. I also updated sequelize-fixtures to the latest version (0.4.3).

I have two tables with these associations
```
    user.belongsToMany(models.group, {
        through: 'user_group',
        foreignKey: 'UserId'
    });

    group.belongsToMany(models.user, {
        through: 'user_group',
        foreignKey: 'GroupId'
    });
```

And i have these fixtures
```
    [
        {
            "model": "group",
            "data": {
                "GroupId": 1,
                "Name": "grp"
            }
        },
        {
            "model": "group",
            "data": {
                "GroupId": 2,
                "Name": "grp 2"
            }
        },
        {
            "model": "user",
            "data": {
                "UserId": 1,
                "UserName":"test",
                "Name":"test",
                "Email":"test@test.is",
                "group": [1]
            }
        },
        {
            "model": "user",
            "data": {
                "UserId": 2,
                "UserName":"test2",
                "Name":"test",
                "group": [2]
            }
        },
        {
            "model": "user",
            "data": {
                "UserId": 3,
                "UserName":"test3",
                "Name":"test",
                "group": [1,2]
            }
        }
    ]
```
Now I'm using this with a in-memory sqlite database.

I have it set so it drops the database and recreates it before each test. The database gets created correctly and the associations are set up.

I get no errors in my log but it doesn't insert the values into the association table. I have tried to type the name of the through table as such
```
{
            "model": "user",
            "data": {
                "UserId": 3,
                "UserName":"test3",
                "Name":"test",
                "user_group": [1,2]
            }
        }
```
But in that case i get a sqlite error that says that the column group.id doesn't exist which it doesn't it's called GroupId.

Any ideas?

**Comment by domasx2** [comment] 2015-05-28 14:46
Hi, 

I think the problem is that sequelize-fixtures assumes that models have primary key attribute named 'id' when trying to find associated entities: https://github.com/domasx2/sequelize-fixtures/blob/master/lib/loader.js#L105

This can be fixed by inspecting dao for the primary key attribute name, I'll update soon. Thanks for the report!

You can work around this by explicitly providing the column name like so:

```javascript
{
    "model": "user",
    "data": {
        "UserId": 3,
        "UserName":"test3",
        "Name":"test",
        "user_group": [
            {
                "GroupId": 1
            },
            {
                "GroupId": 2
            }
        }
    }
}
```

As to why `"group":[1, 2]` is not recognized - m2m relationship must be referened either 'as' relationship name which is pluralized by sequelize, eg `"groups":[1, 2]`, or `through` table name. Should to add some warnings/errors about this

**Comment by Sk1Zy** [comment] 2015-05-28 14:53
Worked like a charm. Thanks :+1:

**Closed** 2015-05-31 10:55 UTC
Labels: bug
